
-- | author: Sushmanth.V.M (CB.EN.U4CYS21077)

import Data.Time.Clock (getCurrentTime)
import Data.Time.Format (formatTime, defaultTimeLocale)


main :: IO ()
-- | The main function that prints the example HTML to the console.
main = do  
    -- | generates the time for the footer
    currentTime <- getCurrentTime
    let formattedTime = formatTime defaultTimeLocale "%Y-%m-%d %H:%M:%S" currentTime
    putStrLn $ generateHtml formattedTime

-- | Constructs the  generateHtml using the 'makeHtml' function.
generateHtml = makeHtml "Haskell Generated HTML" "My dad is my inspiration"



-- | Combines the HTML components to create a full HTML document.
makeHtml title content footer = html_
    (head_ (metaCharset <> metaViewport <> title_ title <> style_ cssStyle) <>
    body_ (header_ (heading_ title) <> main_ (paragraph "Content generated by Haskell:" <> div_ contentDiv) <> footer_ (paragraph ("Generated on: " <> footer))))

-- | Constructs the example HTML using the 'makeHtml' function.
html_ content = "<!DOCTYPE html>" <> content <> "</html>"

-- | Wraps content in head tags.
head_ content = "<head>" <> content <> "</head>"


metaCharset = "<meta charset=\"UTF-8\">"


metaViewport = "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"

-- | Wraps content in style tags.
style_ content = "<style>" <> content <> "</style>"

-- | Wraps content in body tags.
body_ content = "<body>" <> content <> "</body>"

-- | Wraps content in header tags.
header_ content = "<header>" <> content <> "</header>"

-- | Wraps content in main tag.
main_ content = "<main>" <> content <> "</main>"


-- | Wraps content in paragarph tags.
paragraph content = "<p>" <> content <> "</p>"

-- | Wraps content in division tags.
div_ content = "<div id=\"haskell-generated-content\">" <> content <> "</div>"

-- | Wraps content in heading tags.
heading_ content = "<h1>" <> content <> "</h1>"

-- | Wraps conent in footer tags.
footer_ content = "<footer>" <> content <> "</footer>"

-- | Wraps content in title tags.
title_ content = "<title>" <> content <> "</title>"


cssStyle = " h1{color:black;}  body{color:black;}"

contentDiv = "My dad is my insipiration"



